### ISSUE TITLE
Can2mqtt service stopping when hot plugging can devices

### ISSUE THREAD

**Issue by github-aem** [mrk-its/can2mqtt#15]
The canbus physical layer we are using is the 5 wire NMEA 2000 standard with the M12 5Pin A-Coded connectors.  We have devices we have to hot plug into the bus.  According to the error below, it appears the can network is going down temporarily.  I will have to verify causation by the hot plugging.  However, the network going down does cause the service to stop with no recovery.  The watchdog is enabled for the service but does not restart the service.  Could an error check be put in to handle the network error and keep retrying?

`s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
++ can2mqtt -i socketcan -s mqtt://something:something@core-mosquitto -c can0 -b 250000 -t homeassistant --sdo-response-timeout 2.0 --firmware-dir /config
2024-11-21 07:14:20 can2mqtt.entities  INFO server: core-mosquitto, extra_auth: {'username': 'something', 'password': 'something', 'port': 1883}
2024-11-21 07:14:21 can.interfaces.socketcan.socketcan INFO Created a socket
2024-11-21 07:14:21 canopen.network    INFO Connected to 'socketcan channel 'can0''
2024-11-21 07:15:06 asyncio            ERROR Exception in callback Notifier._on_message_available(<can.interfac... 0x7f83c09250>)
handle: <Handle Notifier._on_message_available(<can.interfac... 0x7f83c09250>)>
Traceback (most recent call last):
  File "/root/.local/lib/python3.11/site-packages/can/interfaces/socketcan/socketcan.py", line 538, in capture_message
    cf, ancillary_data, msg_flags, addr = sock.recvmsg(
                                          ^^^^^^^^^^^^^
OSError: [Errno 100] Network is down
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/lib/python3.11/asyncio/events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "/root/.local/lib/python3.11/site-packages/can/notifier.py", line 143, in _on_message_available
    if msg := bus.recv(0):
              ^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/can/bus.py", line 127, in recv
    msg, already_filtered = self._recv_internal(timeout=time_left)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/can/interfaces/socketcan/socketcan.py", line 751, in _recv_internal
    msg = capture_message(self.socket, get_channel)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/can/interfaces/socketcan/socketcan.py", line 546, in capture_message
    raise can.CanOperationError(
can.exceptions.CanOperationError: Error receiving: Network is down [Error Code 100]
2024-11-21 07:15:14 asyncio            ERROR Exception in callback Notifier._on_message_available(<can.interfac... 0x7f83c09250>)
handle: <Handle Notifier._on_message_available(<can.interfac... 0x7f83c09250>)>
Traceback (most recent call last):
  File "/root/.local/lib/python3.11/site-packages/can/interfaces/socketcan/socketcan.py", line 538, in capture_message
    cf, ancillary_data, msg_flags, addr = sock.recvmsg(
                                          ^^^^^^^^^^^^^
OSError: [Errno 100] Network is down
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/lib/python3.11/asyncio/events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "/root/.local/lib/python3.11/site-packages/can/notifier.py", line 143, in _on_message_available
    if msg := bus.recv(0):
              ^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/can/bus.py", line 127, in recv
    msg, already_filtered = self._recv_internal(timeout=time_left)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/can/interfaces/socketcan/socketcan.py", line 751, in _recv_internal
    msg = capture_message(self.socket, get_channel)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/can/interfaces/socketcan/socketcan.py", line 546, in capture_message
    raise can.CanOperationError(
can.exceptions.CanOperationError: Error receiving: Network is down [Error Code 100]
2024-11-21 07:15:21 can2mqtt.entities  INFO quitting: watchdog timeout, exit_code: 42
2024-11-21 07:15:21 can2mqtt.entities  INFO publishing offline status
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped`

**Comment by mrk-its** [comment]
Thanks for the bug report, I'll think what to do with that.
Are you using can2mqtt as addon in HA suprevised? If so, do you have the 'Watchdog' enabled here:

![Screenshot from 2024-11-21 22-04-57](https://github.com/user-attachments/assets/22c405d6-9a3e-4731-9d03-80a4ceb096f9)

I think it should restart can2mqtt for you automatically.

**Comment by github-aem** [comment]
I do have the watchdog service enabled which was what was so odd.

**Comment by mrk-its** [comment]
Hmm, so it is strange that HA supervisor's watchdog didn't start the addon again.

In your logs i see the can2mqtt stopped because of:

```
INFO quitting: watchdog timeout, exit_code: 42 
```

can2mqtt has its own internal watchdog - it is reseted when any heartbeat is received from the bus. But when heartbeat messages are not visible for defined timeout (by default 60 seconds) the addon stops (and can be reinitialized again by HA supervisor).

You can try to increase this timeout by providing `--watchdog-timeout` (or `-w`) parameter via `extra_args` on addon's config page - maybe the network will be available again and can2mqtt will not stop this way.
